@ECHO OFF 

IF not exist %CRUFT4J_HOME% set %CRUFT4J_HOME% = "."

SET CLASSPATH=%CRUFT4J_HOME%\lib\cruft4j-calculator-1.0.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\ant-1.8.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\ant-launcher-1.8.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\ant-testutil-1.7.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\asm-3.2.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\ccl-29.50.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\commons-codec-1.3.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\commons-collections-3.2.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\commons-logging-1.1.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\dom4j-1.6.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\groovy-all-2.0.0.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\h2-1.3.170.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\http-builder-0.5.2.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\httpclient-4.0.3.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\httpcore-4.0.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\javacc-4.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\javancss-32.53.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\jaxen-1.1.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\jcommander-1.27.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\jdom-1.0.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\jhbasic-29.50.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\json-lib-2.3-jdk15.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\junit-4.4.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\pmd-5.0.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\rhino-1.7R3.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\saxon-9.1.0.8.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\saxon-9.1.0.8-dom.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\xercesImpl-2.9.1.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\xml-apis-1.3.0.2.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\xmlParserAPIs-2.6.2.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\xml-resolver-1.2.jar
SET CLASSPATH=%CLASSPATH%;%CRUFT4J_HOME%\lib\xom-1.0.jar

java -classpath %CLASSPATH% org.summalabs.cruft4j.calculator.calc.ScoreCalculator %1 %2 %3 %4 %5 %6 %7 %8 %9 